train:
  limit: 500

  _target_: src.datasets.ASVSpoofDataset

  dataset_dir: data/LA/ASVspoof2019_LA_train

  protocol_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt

  sample_rate: 16000

  instance_transforms: ${transforms.instance_transforms.train}


val:
  limit: 100
  _target_: src.datasets.ASVSpoofDataset

  dataset_dir: data/LA/ASVspoof2019_LA_dev

  protocol_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt

  sample_rate: 16000

  instance_transforms: ${transforms.instance_transforms.inference}


test:
  limit: 100
  _target_: src.datasets.ASVSpoofDataset

  dataset_dir: data/LA/ASVspoof2019_LA_eval

  protocol_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt

  sample_rate: 16000

  instance_transforms: ${transforms.instance_transforms.inference}