defaults:
  - model: lcnn
  - writer: wandb
  - metrics: eer
  - datasets: asvspoof
  - dataloader: example
  - transforms: stft
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.5
loss_function:
  _target_: src.loss.CrossEntropyLoss
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: null
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_EER"
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
