defaults:
  - baseline
  - _self_

datasets:
  train:
    limit: 64
  val:
    limit: 64

dataloader:
  batch_size: 64

trainer:
  n_epochs: 200
  log_step: 1
  save_period: 50
  early_stop: null
  override: True
  monitor: "off"